[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["Lucy <lucy@absolucy.moe>"]
edition = "2021"
license = "0BSD"
repository = "https://github.com/Absolucy/meowtonin"
rust-version = "1.80"
version = "0.1.0"
