[package]
name = "meowtonin"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
simplelog = "0.12"
ahash = { version = "0.8", default-features = false, features = ["no-rng"] }
backtrace = "0.3"
byondapi-sys = { path = "../sys" }
bytemuck = { version = "1", features = ["extern_crate_std"] }
cfg-if = "1"
inventory = "0.3"
libloading = { workspace = true }
meowtonin-impl = { path = "../impl" }
nohash-hasher = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
static_init = "1"
thiserror = "1"
log = "0.4"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.52", features = ["Win32_Foundation", "Win32_System", "Win32_System_Console"] }
